export function isSvg(node, options){
  return (options && options.svg) ||
  node.type === 'svg' ||
  (options && options.svg === true) ||
  (node.type &&
    [
      'svg',
      'path',
      'circle',
      'rect',
      'line',
      'polygon',
      'polyline',
      'ellipse',
      'text',
      'g',
      'defs',
      'use',
      'symbol',
      'mask',
      'clipPath',
      'filter',
      'feGaussianBlur',
      'feOffset',
      'feMerge',
      'feMergeNode',
      'feComposite',
      'feBlend',
      'feColorMatrix',
      'feComponentTransfer',
      'feFuncR',
      'feFuncG',
      'feFuncB',
      'feFuncA',
      'feConvolveMatrix',
      'feDisplacementMap',
      'feFlood',
      'feImage',
      'feMorphology',
      'feSpecularLighting',
      'feDiffuseLighting',
      'feDistantLight',
      'fePointLight',
      'feSpotLight',
      'feTile',
      'feTurbulence',
      'feDropShadow',
    ].includes(node.type))
}